<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col menu_fixed">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="./" class="site_title"><?php echo (Config::array_get($parameters, 'logo')); ?> <span><?php echo (Config::array_get($parameters, 'application', 'Default Application')); ?></span></a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <?php echo Config::get_image(Config::array_get($parameters, 'profile-picture', 'img.jpg'), ['alt' => '', 'class' => "img-circle profile_img"]); ?> 
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2><?php echo (Config::array_get($parameters, 'full-name', 'Samuel Yout')); ?></h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3><?php echo (Config::array_get($parameters, 'responsibility', 'Human Resource')); ?></h3>
                            <ul class="nav side-menu">
                                <?php
                                echo $content['menu'];
//                                
                                ?>
                            </ul>
                        </div>
                    </div>
                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">

                        <?php echo $quick_access; ?>

                        <a data-toggle="tooltip" data-placement="top" title="Collapse" class="menu_toggle" >
                            <i class="fa fa-compress" aria-hidden="true"></i>
                        </a>

                        <a data-toggle="tooltip" data-placement="top" title="Top" id="back-to-top">
                            <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
                        </a>

                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a class="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <?php echo Config::get_image(Config::array_get($parameters, 'profile-picture', 'img.jpg'), ['alt' => '']); ?> 
                                    <?php echo (Config::array_get($parameters, 'full-name', 'Samuel Yout')); ?>
                                    <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <?php
                                    echo Config::array_get($user_action, 'menu');
                                    ?>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->

            <!-- page content -->
            <div class="right_col" role="main" >
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2><?php echo (Config::array_get($parameters, 'title', '')); ?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                    </li>
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                                <?php
                                $content_load = '404.part.phtml';
                                if (Config::array_get($user_action, 'load')):
                                    $content_load = Config::array_get($user_action, 'load');
                                elseif (Config::array_get($content, 'load')):
                                    $content_load = Config::array_get($content, 'load');
                                endif;
                                $load = __DIR__ . '/' . $content_load;
                                if (file_exists($load)) {
                                    require $load;
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /page content -->

            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    <?php echo (Config::array_get($parameters, 'application', 'Default Application') . ' | All rights reserved | &copy; ' . date('Y')); ?>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->

        </div>
    </div>
