<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="./assets/static/images/favicon.ico" type="image/x-icon" />
        <title><?php echo (Config::array_get($parameters, 'title', 'Default Title')); ?></title>
        <?php echo Config::get_assets(Config::array_get($parameters, 'styling', 'stylesheet')); ?>
    </head>

