format-01: &default-button |
 <div class="ln_solid"></div>
 <div class="form-group">
   <div class="col-md-6 col-md-offset-3">
     %s
    </div>
 </div>


format-02 : &default-label |
  <label class="%s" for="%s">%s <span class="required">*</span></label>

format-03 : &default-field |
  <div class="item form-group">
      %s
      <div class="col-md-6 col-sm-6 col-xs-12">
        %s
        <i class="%s" aria-hidden="true"></i>
      </div>
  </div>

format-04 : &default-form |
    <form %1$s>
        %2$s
        <input type="hidden" value="%3$s" name="%4$s[action]"/>
        <input type="hidden" value="%6$s" name="%4$s[runid]"/>
        %5$s
    </form>

customer:
    name : customer
    label-format  : *default-label
    field-format  : *default-field
    button-format : *default-button
    form-format   : *default-form
    attributes :
        action : './controllers/actions.php?controller=customer'
        class : form-horizontal form-label-left
        novalidate : novalidate
        method : post
    fields : 
        - first_name :
            tag : input
            label : 
                text : First Name
                class : control-label col-md-3 col-sm-3 col-xs-12
            attributes :
                type : text
                required : required
                placeholder : First Name
                pattern : alpha
                class : form-control has-feedback-left               
            icon : fa fa-user form-control-feedback left
        - last_name :
            tag : input
            label : 
                text : Last Name
                class : control-label col-md-3 col-sm-3 col-xs-12
            attributes :
                type : text
                required : required
                placeholder : Last Name
                pattern : alpha
                class : form-control has-feedback-left               
            icon : fa fa-user form-control-feedback left
        - national_id :
            tag : input
            label : 
                text : National ID
                class : control-label col-md-3 col-sm-3 col-xs-12
            attributes :
                type : text
                required : required
                placeholder : National ID
                pattern : numeric
                class : form-control has-feedback-left               
            icon : fa fa-id-card-o form-control-feedback left
        - phone :
            tag : input
            label : 
                text : Phone Number
                class : control-label col-md-3 col-sm-3 col-xs-12
            attributes :
                type : text
                required : required
                data-inputmask : "'mask' : '+254-799-999-999'"
                pattern : '[\+]\d{3}-[\d]{3}-[\d]{3}-[\d]{3}'
                placeholder : Phone Number
                class : form-control has-feedback-left               
            icon : fa fa-phone form-control-feedback left
        - email :
            tag : input
            label : 
                text : Email
                class : control-label col-md-3 col-sm-3 col-xs-12
            attributes :
                type : email
                required : required
                placeholder : Email
                class : form-control has-feedback-left               
            icon : fa fa-envelope-o form-control-feedback left 
        - date_of_birth :
            tag : input
            label : 
                text : Date of Birth
                class : control-label col-md-3 col-sm-3 col-xs-12
            attributes :
                data-min-age : 18
                data-min-age-period : years
                type : text
                required : required
                placeholder : Date Of Birth
                readonly : readonly
                class : form-control has-feedback-left date-picker-ro              
            icon : fa fa-calendar form-control-feedback left
            
        - gender :
            tag : select
            label : 
                text : Gender
                class : control-label col-md-3 col-sm-3 col-xs-12
            attributes :
                class : form-control has-feedback-left   
                required : required
            icon : fa fa-user-o form-control-feedback left
            options: get_genders               
            
        - staff_group :
            tag : select
            label : 
                text : Staff Group
                class : control-label col-md-3 col-sm-3 col-xs-12
            attributes :
                class : form-control has-feedback-left 
                required : required 
            icon : fa fa-users form-control-feedback left
            options : get_user_groups
            
        - active :
            tag : select
            label : 
                text : User Account
                class : control-label col-md-3 col-sm-3 col-xs-12
            attributes :
                class : form-control has-feedback-left 
                required : required 
            icon : fa fa-users form-control-feedback left
            options : get_user_actions
    buttons:
        - send : 
            attributes :
                type : submit
                class: btn btn-success pull-right
                text : Submit
            